name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Build release
        run: python3 ./tools/build.py ${{ github.ref_name }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*.zip
          generate_release_notes: true
